
export const DashboardType = {
  TEST: 'TEST'
};

export const LoginType = {
  AUTHENTICATE: 'AUTHENTICATE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS'
};

export const ErrorType = {
  ERROR_LOG: 'ERROR_LOG'
};


export const ReportsType = {
  GET_REPORTS: 'GET_REPORTS',
  GET_DATASOURCE_LIST: 'GET_DATASOURCE_LIST',
  UPDATE_REPORT_DATA: 'UPDATE_REPORT_DATA',
  UPDATE_REPORT_DEFINITION: 'UPDATE_REPORT_DEFINITION',
  UPDATE_REPORT_DATASOURCE: 'UPDATE_REPORT_DATASOURCE',
  SELECT_REPORT: 'SELECT_REPORT',
  SAVE_REPORT: 'SAVE_REPORT',
  // GET_FILTER_RESULTS: 'GET_FILTER_RESULTS',
  SAVE_NEW_REPORT: 'SAVE_NEW_REPORT',
  DELETE_REPORT: 'DELETE_REPORT',
  REPORT_ERROR: 'REPORT_ERROR',
  EXPORT_EXCEL_REPORT: 'EXPORT_EXCEL_REPORT',
  DOWNLOAD_REPORT: 'DOWNLOAD_REPORT',
  EXPORT_PIVOT_REPORT: 'EXPORT_PIVOT_REPORT'
};
